### PR TITLE
Easing function:  linearEaseInOut

### PR DESCRIPTION
**Pull request by sambernaerdt**
When working with longer animations (60s and above), default easing functions tend to result in a very slow start, very fast speeds in the middle and again a very slow stop. The easing function **linearEaseInOut** results in a steady zoom speed, while also easing in and easing out.

### CODE REVIEW

**Comment by mwydmuch** [comment]
Good observation and idea to add a more delicate easing function, but I find the proposed one to be a bit difficult to describe adequately and not that natural. I think the better idea is to have a general family of power-based, easing functions. I've added it in 5c6dd310c90ca0c358764f5565879d13ef63ec11. By using `-e easeIn/Out/InOutPow --easing-power X` with values X between 1 (gives linear easing) and 2 (gives quad easing), one can get more delicate easing. What do you think? Does it solves the problem or do you think that it's a good idea to also include yours?

**Comment by sambernaerdt** [comment]
I think the addition of a custom power easing function is definitely a good idea and add some nice flexibility. The default easing function (and other power-based ones) will still result in the nicest effect for shorter animations (and thus the most use-cases)

But, i don't believe it would achieve the effect I was going for. I'd like a long (e.g. 100s) zoom animation with a linear speed, but still accelerate in the beginning (from speed 0 to a constant speed) and decelerate at the end. You can see the effect here: https://www.instagram.com/p/Cu1CNOzt8QN/

The problem with the power-based easing is that it will either:
- result in a very slow speed in the beginning for a long time -  e.g. `^1.5`
- result in a abrupt start (no noticeable easing) - e.g. `^1.1`

More visually: https://www.desmos.com/calculator/mdat9lpd9u, when looking at the range [0 - 0.01]. 
image
(green `x ** 1.5`, red (ease in) + blue (linear) is the effect I am going for)

So, I do think there is a reason for the `linearEaseInOut`, but I also agree that it is a bit clumsy in the readme, a confusting name and hard to describe / explain.

**Comment by mwydmuch** [comment]
Ok, you are right that, for very long animations, power-based easing might not give you such a smooth start. Let's merge it, but could you first adjust it to the design that it's used in the main branch now? 

Not sure about it, but maybe it would be better to name it `linearWithInOutEase` or in a similar fashion? 
I will write a short note on easing functions later.

**Comment by sambernaerdt** [comment]
> 

`linearWithInOutEase` is a lot clearer! 

I'm about to leave on Holidays. I will pick this up when we're back in a few weeks...

**Comment by mwydmuch** [comment]
Ok, then I will do it this weekend and merge it :) Enjoy your holidays/vacations!

**Comment by mwydmuch** [comment]
Done. Thank you for the PR and idea @sambernaerdt!

**Comment by sambernaerdt** [comment]
Super! Thanks a lot!!

**Pull request merged**
